# Ejercicios clase 5

## Paso 1 Importación

In [5]:
import pandas as pd
import numpy as np

## Paso 2 Cargar archivo

In [6]:
df = pd.read_csv("dataset_tiempo_entrega.csv")

In [7]:
df.columns

Index(['zona', 'tiempo_entrega_horas'], dtype='object')

In [ ]:
df.columns

     zona  tiempo_entrega_horas
0  Centro                  39.0
1  Centro                  35.2
2   Norte                  39.9
3   Norte                  45.1
4   Norte                  34.6
5     Sur                  34.6
6  Centro                  45.5
7     Sur                  40.6
8   Norte                  33.2
9  Centro                  39.3

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   zona                  205 non-null    object
 1   tiempo_entrega_horas  205 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.3+ KB

In [13]:
print(df.isnull().sum())

zona                    0
tiempo_entrega_horas    0
dtype: int64

## Transformar valores a Numericos

In [15]:
df["tiempo_entrega_horas"] = pd.to_numeric(df["tiempo_entrega_horas"], errors="coerce")
df

       zona  tiempo_entrega_horas
0    Centro                  39.0
1    Centro                  35.2
2     Norte                  39.9
3     Norte                  45.1
4     Norte                  34.6
..      ...                   ...
200  Centro                  80.0
201   Norte                  90.0
202   Norte                 120.0
203  Centro                 150.0
204   Norte                 200.0

[205 rows x 2 columns]

## Medidas de Tendencia Central

In [16]:
media = df["tiempo_entrega_horas"].mean()
print("La media de tiempos de entrega es: ", media)

La media de tiempos de entrega es:  38.00536585365854

In [18]:
mediana = df["tiempo_entrega_horas"].median()
print("La mediana es: ", mediana)

La mediana es:  36.3

In [19]:
moda = df["tiempo_entrega_horas"].mode()
print("La moda es: ", moda)

La moda es:  0    40.9
Name: tiempo_entrega_horas, dtype: float64

## Medidas de Disperción

### Varianza

In [20]:
varianza = df["tiempo_entrega_horas"].var()
varianza

280.3576671449067

### Desviación estandar

In [21]:
desv_std = df["tiempo_entrega_horas"].std()
desv_std

16.74388447000596

### Coeficiente de Variación

In [22]:
coef_var = (desv_std / media) * 100
coef_var

np.float64(44.05663277780059)

### Datos agrupados por zona

In [37]:
resumen_p_zona = df.groupby("zona")["tiempo_entrega_horas"].agg(
    ["mean", "median", "var", "std", "count"])
resumen_p_zona

             mean  median         var        std  count
zona
Centro  37.516667    35.7  233.066479  15.266515     72
Norte   39.871429    36.5  504.297068  22.456560     77
Sur     36.067857    36.6   33.147675   5.757402     56

In [ ]:
resumen_p_zona =[]

In [ ]:
resumen_p_zona.sort

In [34]:
print(f"El tiempo promedio de entregas es {media:.2f} horas")
print(f"La mediana es {mediana:.2f} horas")

El tiempo promedio de entregas es 38.01 horas
La mediana es 36.30 horas

In [35]:
if media > mediana:
    print("La media es mayor q la mediana, lo sugiete valores extremos altos")
elif media < mediana:
    print("La media es menor q la mediana, lo sugiete valores extremos bajos")
else:
    print("La media y mediana son similares")

La media es mayor q la mediana, lo sugiete valores extremos altos

In [36]:
zona_mayor_media = resumen_p_zona["median"].idxmax()
zona_mayor_media

'Sur'

In [ ]:
zona_mayor_cv = resumen_p_zona["coef"]

## Actividad práctica

In [38]:
df = pd.read_csv("insurance.csv")